# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI / CD workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-deploy:
    name: Test and deploy
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        node-version: [15.x, 16.x]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install
      run: yarn install
    - name: Test
      run: npm test
    - name: Deploy
      if: ${{ matrix.node-version == '16.x' && matrix.os == 'ubuntu-latest' }}  
      env:
        NODE_ENV: production
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: | 
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/bdnkl/digital-hometown-frontend.git
          npm run deploy
 
